language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache: pip

install:
  - "pip install flake8 pytest pytest-cov wheel"

before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"

script:
  - "flake8 --ignore=F401 tests inputimeout"
  - "py.test -s --cov inputimeout tests/"
  - "python setup.py bdist_wheel"

after_script:
  - "coverage xml"
  - "./cc-test-reporter after-build"