name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Install dev dependencies
        run: |
          poetry install
      - name: Run test
        run: |
          poetry run pytest -s --cov=inputimeout tests/
      - name: Upload coverage
        run: |
          poetry run codecov -t ${{ secrets.CODECOV_TOKEN }}
